syntax on
set smarttab
set autoindent
set expandtab
set backspace=2

set shiftwidth=4
set tabstop=4

filetype indent on
filetype plugin on

set number relativenumber
set ignorecase
set smartcase
set autoread
set hlsearch
set showmatch
set encoding=utf8
set ffs=unix,dos,mac

set backup
set undofile

set history=1200
set undolevels=1000
set undoreload=8000

set undodir=$HOME/.local/share/vim/undo
set backupdir=$HOME/.local/share/vim/backup
set directory=$HOME/.local/share/vim/swap

nnoremap <Leader><Leader>ev :tabnew<CR>:e $HOME/.config/vim/vimrc<CR>
nnoremap <Leader><Leader>w :w<CR>
nnoremap <Leader><Leader>wq :wq<CR>
nnoremap <Leader><Leader>q :q<CR>
