live_config_reload = true

# import = ["/root/.config/alacritty/colorscheme/themes/atlantic.toml"]
# import = ["/root/.config/alacritty/colorscheme/themes/atlantic-black.toml"]
# import = ["/root/.config/alacritty/colorscheme/themes/zenburn.toml"]
# import = ["/root/.config/alacritty/colorscheme/themes/omni.toml"]
# import = ["/root/.config/alacritty/colorscheme/themes/nord.toml"]
import = ["/root/.config/alacritty/colorscheme/themes/zhxo.toml"]

[shell]
program = "/usr/bin/fish"

[window.padding]
# x = 5
# y = 5

[window]
dynamic_padding = false
decorations = "Full"
opacity = 0.8
blur = false
dynamic_title = true

[scrolling]
history = 16000
multiplier = 3

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 10
builtin_box_drawing = false

[font.normal]
# family = "Maple Mono NF"
# family = "JetBrainsMono Nerd Font"
family = "Fira Code Nerd Font"
style = "Regular"

[font.bold]
# family = "Maple Mono NF"
# family = "JetBrainsMono Nerd Font"
family = "Fira Code Nerd Font"
style = "Bold"

[font.italic]
# family = "Maple Mono NF"
# family = "JetBrainsMono Nerd Font"
family = "Fira Code Nerd Font"
style = "Italic"

[font.bold_italic]
# family = "Maple Mono NF"
# family = "JetBrainsMono Nerd Font"
family = "Fira Code Nerd Font"
style = "Bold Italic"

# [font.offset]
# x = 0
# y = 0

[selection]
save_to_clipboard = false

[cursor.style]
shape = "Beam"
blinking = "On"

[cursor]
blink_interval = 750
blink_timeout = 5

[mouse]
hide_when_typing = false

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
action = "ScrollToTop"
