live_config_reload = true

# import = ["/home/paodelonga/.config/alacritty/colorscheme/themes/atlantic.toml"]
# import = ["/home/paodelonga/.config/alacritty/colorscheme/themes/atlantic-black.toml"]
# import = ["/home/paodelonga/.config/alacritty/colorscheme/themes/zenburn.toml"]
# import = ["/home/paodelonga/.config/alacritty/colorscheme/themes/omni.toml"]
# import = ["/home/paodelonga/.config/alacritty/colorscheme/themes/nord.toml"]
import = ["/home/paodelonga/.config/alacritty/colorscheme/themes/zhxo.toml"]

[shell]
program = "/usr/bin/fish"

[window.padding]
# x = 5
# y = 5

[window]
dynamic_padding = false
decorations = "Full"
opacity = 0.8
blur = false
dynamic_title = true

[scrolling]
history = 16000
multiplier = 3

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12
builtin_box_drawing = true

[font.normal]
family = "ComicShannsMonoNerdFont"
# family = "Maple Mono NF"
style = "Regular"

[font.bold]
family = "ComicShannsMonoNerdFont"
# family = "Maple Mono NF"
style = "Bold"

[font.italic]
family = "ComicShannsMonoNerdFont"
# family = "Maple Mono NF"
style = "Italic"

[font.bold_italic]
family = "ComicShannsMonoNerdFont"
# family = "Maple Mono NF"
style = "Bold Italic"

[selection]
save_to_clipboard = false

[cursor.style]
shape = "Beam"
blinking = "On"

[cursor]
blink_interval = 350
blink_timeout = 5

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
action = "SpawnNewInstance"
